services:
  - type: web
    name: 4k-video-upscaler
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn main:app --workers=1 --threads=2 --timeout=600
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    plan: free
    healthCheckPath: /check
    autoDeploy: true
